---
title: "Figure 1"
author: "Pietro Demela"
date: "10/01/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
knitr::opts_knit$set(root.dir =  "/project/aid_sharing/AID_sharing") #set up the project directory
```

## Figure 1A

### Libraries

```{r}
library(corrplot)
```


### Correlation matrix

```{r}
#load the ldsc output
ldsc_ok <- readRDS('outputs/rev_1/02_munge_ldsc_sumstats/ldsc_output_rev1.RDS')

#rename the columns with uppercase names in the right order
colnames(ldsc_ok$S_Stand)
names_plot = c('T1D','CD', 'UC', 
               'PSC', 'JIA', 'SLE', 
               'RA',  'Ast', 'Ecz')


#rename columns and rows
rownames(ldsc_ok$S_Stand) <- names_plot
colnames(ldsc_ok$S_Stand) <- names_plot

#reorder
plot <- ldsc_ok$S_Stand[c('CD', 'UC','PSC', 'JIA', 'SLE','RA','T1D', 'Ast', 'Ecz'),c('CD', 'UC','PSC', 'JIA', 'SLE','RA','T1D', 'Ast' , 'Ecz')]

#save
pdf('outputs/rev_1/Figures/Fig_1/1A_correlation_matrix.pdf', height = 14, width = 14)
corrplot(plot, 
         order = 'original',
         addCoef.col = 'black', 
         method = 'square',
         type = 'upper', 
         is.corr = T,
         tl.col='black',
         outline=F,
         number.cex= 1.5,
         tl.cex=1.5,
         cl.cex=1.5,
         tl.srt= 45,
         addgrid.col='grey', 
         title= 'LDSC genetic correlation matrix of autoimmune diseases', mar=c(0,0,1,0)
)

dev.off()

#plot
corrplot(plot, 
         order = 'original',
         addCoef.col = 'black', 
         method = 'square',
         type = 'upper', 
         is.corr = T,
         tl.col='black',
         outline=F,
         number.cex= 1,
         tl.cex=1.5,
         cl.cex=1.5,
         tl.srt= 45,
         addgrid.col='grey', 
         title= 'LDSC genetic correlation matrix of autoimmune diseases', mar=c(0,0,1,0)
)
```


## Figure 1B

### Libraries

```{r message=FALSE, warning=FALSE}
library(data.table)
library(GenomicSEM)
library(Matrix)
library(tidyr)
library(dplyr)
library(corrplot)
library(qgraph)
library(semPlot)
library(lavaan)
library(RColorBrewer)
library(gridExtra)
```

### Function for SEM pathways

Function that allows to plot the output of usermodel with pathview
```{r}

semPlotModel_GSEM=function(gsem.object=GWISoutput , est.label="STD_All"){ 
  require(semPlot)
  object=gsem.object$results
  object$free=0
  numb=1:length(which(object$op!="~~"))
  object$free[which(object$op!="~~")]=numb
  varNames <- lavaanNames(object, type = "ov")
  factNames <- lavaanNames(object, type = "lv")
  factNames <- factNames[!factNames %in% varNames]
  n <- length(varNames)
  k <- length(factNames)
  if (is.null(object$label)) 
    object$label <- rep("", nrow(object))
  semModel <- new("semPlotModel")
  object$est <- object[,est.label]
  if (is.null(object$group)) 
    object$group <- ""
  semModel@Pars <- data.frame(label = object$label, lhs = ifelse(object$op == 
                                                                   "~" | object$op == "~1", object$rhs, object$lhs), edge = "--", 
                              rhs = ifelse(object$op == "~" | object$op == "~1", object$lhs, 
                                           object$rhs), est = object$est, std = NA, group = object$group, 
                              fixed = object$free==0, par = object$free, stringsAsFactors = FALSE)
  semModel@Pars$edge[object$op == "~~"] <- "<->"
  semModel@Pars$edge[object$op == "~*~"] <- "<->"
  semModel@Pars$edge[object$op == "~"] <- "~>"
  semModel@Pars$edge[object$op == "=~"] <- "->"
  semModel@Pars$edge[object$op == "~1"] <- "int"
  semModel@Pars$edge[grepl("\\|", object$op)] <- "|"
  semModel@Thresholds <- semModel@Pars[grepl("\\|", semModel@Pars$edge), 
                                       -(3:4)]
  semModel@Pars <- semModel@Pars[!object$op %in% c(":=", "<", 
                                                   ">", "==", "|", "<", ">"), ]
  semModel@Vars <- data.frame(name = c(varNames, factNames), 
                              manifest = c(varNames, factNames) %in% varNames, exogenous = NA, 
                              stringsAsFactors = FALSE)
  semModel@ObsCovs <- list()
  semModel@ImpCovs <- list()
  semModel@Computed <- FALSE
  semModel@Original <- list(object)
  return(semModel)
  
}



```


### Path model

```{r message=TRUE, warning=TRUE, paged.print=FALSE}

#load the ldsc output
ldsc_ok <- readRDS('outputs/rev_1/02_munge_ldsc_sumstats/ldsc_output_rev1.RDS')


# the factor model 
aid_model <-'F1 =~ NA*crohn + uc  + psc  
F2 =~ NA*jia + sle + ra + t1d 
F3 =~ NA*asthma + derma 

F1~~F2
F1~~F3
F2~~F3
F1 ~~ 1*F1
F2 ~~ 1*F2
F3 ~~ 1*F3
derma~~a*derma
a>0.001
'

aid_factor <-usermodel(ldsc_ok, estimation = "DWLS", model = aid_model, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)
signif(aid_factor$modelfit,2)


#save
pdf('outputs/rev_1/Figures/Fig_1/1B_three_factor_model.pdf', height = 20, width = 18)
semPaths(semPlotModel_GSEM(aid_factor), 
         what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 8, 
         sizeInt = 10,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 12,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2', 'F3' ), 
         label.cex = 1.5, 
         color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 18, width = 18, 
         edge.label.position=0.5,
         asize=3,
         esize=1,
         
)
dev.off()


#plot 
semPaths(semPlotModel_GSEM(aid_factor), 
         what = 'path' , 
         whatLabels= 'est',
         residuals = T, 
         sizeMan = 8, 
         sizeInt = 10,
         label.cex=1, 
         theme="colorblind", 
         rotation = 4, 
         layout = "tree2", 
         sizeLat = 12,
         edge.color = "black",
         edge.label.cex = 1,
         curve = 2,
         nodeLabels = c('CD', 'UC', 'PSC', 'JIA', 
                        'SLE', 'RA','T1D' ,'AST', 'ECZ' , 'F1', 'F2', 'F3' ), 
         label.cex = 1.5, 
         color = list( lat=brewer.pal(12, 'Paired')[c(1,3,5)]),
         groups=list(c("crohn","uc","psc"),c("jia","sle","ra_eu","t1d"), c( "asthma" ,"derma")),
         height = 18, width = 18, 
         edge.label.position=0.5,
         asize=3,
         esize=1,
         
)
```


## Figure 1C

### Libraries 

```{r message=FALSE, warning=FALSE}
library(data.table)
library(qqman)
library(dplyr)
library(CMplot)
library(rcartocolor)
library(RColorBrewer)
```

### Man plot

```{r}

#load the summary statistics
gw <- list()

for(i in c(1:3)){
  tt <- c('f1', 'f2', 'f3')[i]
  gw[[tt]] <- fread(paste0('outputs/rev_1/03_gwas_estimation/summarystats_/',tt,'_.txt' ),
                    data.table = F)
}


SNPs <- unique(c(gw[['f1']]$SNP, gw[['f2']]$SNP, gw[['f3']]$SNP ))
circular <- data.frame('SNP'=SNPs)

circular[,c('CHR')] <- gw[['f1']][match(circular$SNP,gw[['f1']]$SNP ),]$CHR
circular[,c('BP')] <- gw[['f1']][match(circular$SNP,gw[['f1']]$SNP ),]$BP

circular[, 'f1'] <- gw[['f1']][match(circular$SNP,gw[['f1']]$SNP ),]$P
circular[, 'f2'] <- gw[['f2']][match(circular$SNP,gw[['f2']]$SNP ),]$P
circular[, 'f3'] <- gw[['f3']][match(circular$SNP,gw[['f3']]$SNP ),]$P




factor_loci <- fread('outputs/2_gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/06_genomic_regions_all_traits_munged/factor.regions.txt', data.table = F) 

#v3

matrix(c(rcartocolor::carto_pal(3, 'Safe')[1],rcartocolor::carto_pal(3, 'Safe')[2],rcartocolor::carto_pal(3, 'Safe')[3],
         RColorBrewer::brewer.pal(4, 'Blues')[4], RColorBrewer::brewer.pal(3, 'Reds')[3], RColorBrewer::brewer.pal(4, 'YlOrRd')[2]),
       3,2,byrow=T)


  CMplot(circular, 
         plot.type="m",
         multracks=TRUE,
         threshold=c(5e-8),
         threshold.lty=c(1,2), 
         threshold.lwd=c(1,1), 
         threshold.col=c("black","grey"), 
         amplify=F,
         #signal.col=list(brewer.pal(12, 'Paired')[c(1)], brewer.pal(12, 'Paired')[3], brewer.pal(12, 'Paired')[c(5)]),
         #signal.pch=c(1),
         signal.cex=0.7,
         col=matrix(c(brewer.pal(12, 'Paired')[c(1,3,5)], brewer.pal(12, 'Paired')[c(2,4,6)]),
                    3,2,byrow=F),
         highlight=list(f1=factor_loci[factor_loci$trait=='f1', ]$SNP, f2=factor_loci[factor_loci$trait=='f2', ]$SNP, f3=factor_loci[factor_loci$trait=='f3', ]$SNP),
         highlight.col='black',
         highlight.pch = 18, 
         highlight.cex=1.6,
         file=c("jpg"),
         memo="v3",
         dpi=300,
         file.output=T,
         verbose=TRUE, 
         LOG10=T,
         chr.border=F,
         cex.lab=2,
         width=50, 
         height=10)

```































