#  LD score regression on auotoimmunity GWAS
##  in this script the selected summary stats will be used to run ldsc, munge and sum stats function
#the have to be in the same order in the function

#The tutorial and info on the package and how to run the code are here:  
#https://github.com/GenomicSEM/GenomicSEM/wiki/5.-User-Specified-Models-with-SNP-Effects

#This script, step4, is for preparing the sumstats to run the GWAS by using the two factor model
#specified in step3. 
# 'Please also note that the sumstats function requires that the variables be listed -
#in the same order as they are listed for the ldsc function.'

#This means that I have to run again the analysis from the munge step for only 
#the GWAS we are keeping in the model. 
#The GWAS included in the three factor model are cuc-cd-psc-ra-sle-t1d-jia-asthma-derma

#--- Load the libraries--------------------------------------
library(data.table)
library(GenomicSEM)
library(tidyr)
library(dplyr)
library(corrplot)
library(extrafont)
loadfonts()

#----CHeck the standard errors--------------------------------------------------

#----- Function to check if the SE are STD error of log(OD)-----
is_se_logB <- function(BETA,SE, PVALUE) {
  p_calculated <- 2*pnorm((abs(BETA) / SE),lower.tail = F)
  p_reported <- PVALUE
  #data.frame(p_calculated, p_reported), 
  a <- lm(p_calculated~p_reported) #fit a linear model to see if they are perfectly correlated 
  print(summary(a))
  
  rand <- sample(1:length(BETA), 10000)
  plot(p_reported[rand], p_calculated[rand]) 
  abline(a, col="red") # regression line (y~x)
  abline(0, 1, col='blue', lty= 4 )
}


#---- crohn SE -----------------------------------------------------------------
cd <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/crohn_delange-2017.txt', data.table = F)
head(cd) 
is_se_logB(cd$Beta, cd$SE, cd$p) #SE logistic beta (effect column is beta as there are negative values)

#----- uc SE --------------------------------------------------------------------
uc <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/uc_delange-2017.txt', data.table = F)
head(uc)
is_se_logB(uc$Beta, uc$SE, uc$p) #SE logistic beta (effect column is beta as there are negative values)

#----- psc SE -------------------------------------------------------------------
psc <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/psc_ji-2016.txt', data.table = F)
head(psc)

is_se_logB(log(psc$OR), psc$SE, psc$P) #SE of logistic beta

#----- jia SE ------------------------------------------------------------------

jia  <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/jia_beta_lopezisac-2020.txt', data.table = F) 
head(jia)
is_se_logB(jia$Beta, jia$SE, jia$p) #SE of logististi bete

#----- sle SE ------------------------------------------------------------------

sle <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/sle_beta_bentham-2015.txt', data.table = F)
head(sle)
is_se_logB(BETA = sle$Beta, SE = sle$SE, PVALUE = sle$p) #SE of logistic beta (effect column is beta as there are negative values)

#----- ra eu okada SE -------------------------------------------------------------------

ra <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/ra_eu_okada-2014.txt', data.table = F)
head(ra)
is_se_logB(BETA = ra$Beta, SE = ra$SE, PVALUE = ra$p) #SE of logistic beta

#-----t1d SE----------------------------------------------------------------------

t1d <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/t1d_chiou-2021.txt', data.table = F)
head(t1d)
is_se_logB(BETA = t1d$effect, SE = t1d$SE, PVALUE = t1d$p) #SE of logistic BETA


#------asthma 2 SE -------------------------------------------------------------

asthma <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/asthma_ban-2020.txt', data.table = F)
head(asthma)
is_se_logB(log(asthma$OR), asthma$SE, asthma$p) #SE of logistic BETA, the analysis is logfistic regression

#----derma SE ---------------------------------------------------------------
derma <- fread('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/derma_sliz-2021.txt', data.table = F)
head(derma)
is_se_logB(derma$Beta, derma$SE, derma$p) #SE of logistic beta, logistic regression checked on paper


#---- Munge the summary stats --------------------------------------------------

#Function for sample prevalence calculation-------------------------------------
#a function for doing it rapidly from csv files 
#csv files generated by me, from info in the papers
calculate_prevalence <- function(path_of_csv){
  #read the file and remove the NA columns and rows
  preva_csv <- read.csv(file = path_of_csv , header = T, sep = ';')
  preva_csv <-  preva_csv[, c('cases', 'controls')]
  preva_csv_noNA <- preva_csv[complete.cases(preva_csv), ]
  
  #calculated effective prevalence 
  #calculate sample prevalence for each cohort
  preva_csv_noNA$v <-preva_csv_noNA$cases/(preva_csv_noNA$cases+preva_csv_noNA$controls)
  #calculate cohort specific effective sample size
  preva_csv_noNA$EffN<-4*preva_csv_noNA$v*(1-preva_csv_noNA$v)*(preva_csv_noNA$cases+preva_csv_noNA$controls)
  #calculate sum of effective sample size: 
  eff_sample_size <- round(sum(preva_csv_noNA$EffN), 3)
  
  #print number of cases and controls, and effective sample size
  cat(paste0( 'Number of cases  ' , sum(preva_csv_noNA$cases), '\n', 
              'Number of contros  ', sum(preva_csv_noNA$controls), '\n', 
              'Effective sample size  ', round(sum(preva_csv_noNA$EffN), 3)
  ))
  
  #output the prevalenc when assigned to a variable 
  invisible(round(eff_sample_size, 3))
}

#---- munge function -----------------------------------------------------------

file_names <- c('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/t1d_chiou-2021.txt', 
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/crohn_delange-2017.txt', 
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/uc_delange-2017.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/psc_ji-2016.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/jia_beta_lopezisac-2020.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/sle_beta_bentham-2015.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/ra_eu_okada-2014.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/asthma_ban-2020.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/derma_sliz-2021.txt'
                )
traits <- c('t1d','crohn', 'uc', 'psc', 'jia', 'sle', 'ra',  'asthma', 'derma')

t1d_p <- calculate_prevalence('Prevalences/CSV_prevalences/t1d_chiou-2021.csv')
crohn_p <- calculate_prevalence('Prevalences/CSV_prevalences/crohn_delange-2017.csv')
uc_p <- calculate_prevalence('Prevalences/CSV_prevalences/uc_delange-2017.csv')
psc_p <- 14890
jia_p <- 12501
sle_p <- calculate_prevalence('Prevalences/CSV_prevalences/sle_benthman-2015.csv')
ra_p <- calculate_prevalence('Prevalences/CSV_prevalences/ra_okada-2014_only-eu.csv')
asthma_p <- 64538 + 239321
derma_p <- calculate_prevalence('Prevalences/CSV_prevalences/derma_sliz-2021.csv')

munge(files = file_names, hm3 = 'SNP/w_hm3.snplist', 
      N = c(t1d_p, crohn_p, uc_p, psc_p, jia_p, sle_p, ra_p, asthma_p, derma_p), 
      trait.names = traits)

system(' mv *.sumstats.gz *log outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/ ')


#-----ldsc function ------------------------------------------------------------
munged_files <- c('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/t1d.sumstats.gz',
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/crohn.sumstats.gz',
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/uc.sumstats.gz',
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/psc.sumstats.gz',
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/jia.sumstats.gz', 
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/sle.sumstats.gz', 
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/ra.sumstats.gz', 
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/asthma.sumstats.gz', 
                  'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/munge_output/derma.sumstats.gz')

names = c('t1d','crohn', 'uc', 'psc', 'jia', 'sle', 'ra',  'asthma', 'derma')




ldsc_output <- ldsc(traits = munged_files, 
                      sample.prev = c(.5, .5, .5, 0.1928, 0.2643, .5, .5, ((64538)/(64538 + 239321)), .5),  
                     population.prev = c(0.095, 0.001, 0.0003, 0.000050, 0.000447, 0.000500,  0.004600, 0.035700, 0.20 ), 
                     trait.names = names,
                     ld = "ldscores/eur_w_ld_chr",
                     wld= "ldscores/eur_w_ld_chr", stand = T)
system('mv *log outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/ldsc_output/')

saveRDS(ldsc_output, 'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/ldsc_output/ldsc_uc-cd-psc-ra-sle-t1d-jia-asthma-derma.RDS')
ldsc_ok <- readRDS('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/ldsc_output/ldsc_uc-cd-psc-ra-sle-t1d-jia-asthma-derma.RDS')



#plot the genetic correlation matrix
names_plot = c('Type 1 Diabetes','Crohn\'s disease', 'Ulcerative colitis', 
               'Primary sclerosing cholangitis ', 'Juvenile idiopathic arthritis', 'Systemic lupus erythematosus', 
               'Rheumatoid arthritis',  'Asthma', 'Atopic dermatitis')
rownames(ldsc_ok$S_Stand) <- names_plot
colnames(ldsc_ok$S_Stand) <- names_plot
pdf('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/correlation_matrix_uc-cd-psc-ra-sle-t1d-jia-asthma-derma.pdf', height = 14, width = 14)
corrplot(ldsc_ok$S_Stand, order = 'hclust',addCoef.col = 'black', method = 'square',type = 'upper', is.corr = T,
        tl.col='black', outline=F,
        number.cex= 1.5,
         tl.cex=1.5,
        cl.cex=1.5,
         tl.srt= 45,
         addgrid.col='grey', 
         family="Helvetica",
        title= 'LDSC genetic correlation matrix of autoimmune diseases', mar=c(0,0,1,0)
         )

dev.off()

?corrplot

#---- Two factor model ---------------------------------------------------------
aid_model <-'F1 =~ NA*crohn + uc  + psc  
F2 =~ NA*jia + sle + ra + t1d 
F3 =~ NA*asthma + derma 

F1~~F2
F1~~F3
F2~~F3
F1 ~~ 1*F1
F2 ~~ 1*F2
F3 ~~ 1*F3
derma~~a*derma
a>0.001
'


#run the model
aid_factor <-usermodel(ldsc_ok, estimation = "DWLS", model = aid_model, CFIcalc = TRUE, std.lv = TRUE, imp_cov = FALSE)
aid_factor

saveRDS(aid_factor, 'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/model_uc-cd-psc-ra-sle-t1d-jia-asthma-derma.RDS') 


#----Sumstat function-----------------------------------------------------------


file_names_ok <- c('outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/t1d_chiou-2021.txt', 
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/crohn_delange-2017.txt', 
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/uc_delange-2017.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/psc_ji-2016.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/jia_beta_lopezisac-2020.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/sle_beta_bentham-2015.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/ra_eu_okada-2014.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/asthma_ban-2020.txt',
                'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/01_qc_sumstats/ready_for_munge/derma_sliz-2021.txt'
)



t1d_p <- calculate_prevalence('Prevalences/CSV_prevalences/t1d_chiou-2021.csv')
crohn_p <- calculate_prevalence('Prevalences/CSV_prevalences/crohn_delange-2017.csv')
uc_p <- calculate_prevalence('Prevalences/CSV_prevalences/uc_delange-2017.csv')
psc_p <- 14890
jia_p <- 12501
sle_p <- calculate_prevalence('Prevalences/CSV_prevalences/sle_benthman-2015.csv')
ra_p <- calculate_prevalence('Prevalences/CSV_prevalences/ra_okada-2014_only-eu.csv')
asthma_p <- calculate_prevalence('Prevalences/CSV_prevalences/asthma_demeanis-2018.csv') #this is wrong but N is not used by sumstats
derma_p <- calculate_prevalence('Prevalences/CSV_prevalences/derma_sliz-2021.csv')




aid_sumstats <-sumstats(files = file_names_ok, ref = 'SNP/reference.1000G.maf.0.005.txt.gz',
                                trait.names = c('t1d','crohn', 'uc', 'psc', 'jia', 'sle', 'ra',  'asthma', 'derma') ,
                                se.logit =  c(T,T,T,T,T,T,T,T,T),  
                                OLS = c(F,F,F,F,F,F,F,F,F), 
                                linprob = c(F,F,F,F,F,F,F,F,F), 
                                N = c(t1d_p, crohn_p, uc_p, psc_p, jia_p, sle_p, ra_p, asthma_p, derma_p), 
                                parallel = T,
                                keep.indel= F 
)

system('mv *log  outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/sumstats_output/')

saveRDS(aid_sumstats, file= 'outputs/gwas_uc-cd-psc-ra-sle-t1d-jia-asthma-derma/04_sumstat_outputs/sumstats_output/sumstats_uc-cd-psc-ra-sle-t1d-jia-asthma-derma.RDS')

#aid_sumstats_noPBC <- readRDS('outputs/version3/04_output_sumstats-function/aid_sumstats_newRA.RDS') 

dim(aid_sumstats) #3 344 158      24
head(aid_sumstats)
#----------------------------------------------------------------------------






calculate_prevalence <- function(path_of_csv){
  #read the file and remove the NA columns and rows
  preva_csv <- read.csv(file = path_of_csv , header = T, sep = ';')
  preva_csv <-  preva_csv[, c('cases', 'controls')]
  preva_csv_noNA <- preva_csv[complete.cases(preva_csv), ]
  
  #calculated effective prevalence 
  #calculate sample prevalence for each cohort
  preva_csv_noNA$v <-preva_csv_noNA$cases/(preva_csv_noNA$cases+preva_csv_noNA$controls)
  #calculate cohort specific effective sample size
  preva_csv_noNA$EffN<-4*preva_csv_noNA$v*(1-preva_csv_noNA$v)*(preva_csv_noNA$cases+preva_csv_noNA$controls)
  #calculate sum of effective sample size: 
  eff_sample_size <- round(sum(preva_csv_noNA$EffN), 3)
  
  #print number of cases and controls, and effective sample size
  cat(paste0( 'Number of cases  ' , sum(preva_csv_noNA$cases), '\n', 
              'Number of contros  ', sum(preva_csv_noNA$controls), '\n', 
              'Effective sample size  ', round(sum(preva_csv_noNA$EffN), 3)
  ))
  
  #output the prevalenc when assigned to a variable 
  
  
  
  return(sum(preva_csv_noNA$cases)/sum(preva_csv_noNA$controls))
}




traits <- c('t1d','crohn', 'uc', 'psc', 'jia', 'sle', 'ra',  'asthma', 'derma')

t1d_p <- calculate_prevalence('Prevalences/CSV_prevalences/t1d_chiou-2021.csv')
crohn_p <- calculate_prevalence('Prevalences/CSV_prevalences/crohn_delange-2017.csv')
uc_p <- calculate_prevalence('Prevalences/CSV_prevalences/uc_delange-2017.csv')
psc_p <- 2871/12019
jia_p <- 3305/9196
sle_p <- calculate_prevalence('Prevalences/CSV_prevalences/sle_benthman-2015.csv')
ra_p <- calculate_prevalence('Prevalences/CSV_prevalences/ra_okada-2014_only-eu.csv')
asthma_p <- 64538/ 239321
derma_p <- calculate_prevalence('Prevalences/CSV_prevalences/derma_sliz-2021.csv')




list(t1d_p=t1d_p, crohn_p=crohn_p, uc_p=uc_p, psc_p=psc_p, jia_p=jia_p, sle_p=sle_p, ra_p=ra_p, asthma_p=asthma_p, derma_p=derma_p)














